# Supported funding platforms
github: [Dev-Sahad]

# Uncomment if you use other platforms
# patreon: your_username
# buy_me_a_coffee: your_username
# ko_fi: your_username
# custom: ["https://your-website.com"]
