name: Update Top Languages

on:
  schedule:
    - cron: "0 */12 * * *" # Completely automatic (Runs every 12 hours)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Top Languages SVG
        run: |
          curl "https://github-readme-stats.vercel.app/api/top-langs/?username=Dev-Sahad&layout=compact&theme=tokyonight&hide_border=true&langs_count=6" -o top-languages.svg

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add Assets/top-languages.svg
          
          # Only proceed if changes exist to avoid empty commit noise
          if ! git diff --staged --quiet; then
            git commit -m "chore: update top-languages.svg"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No language stats changes detected."
          fi
          
